### PR TITLE
Expose cacheDir as an option

### PR DESCRIPTION
**Pull request by joeybaker**

### CODE REVIEW

**Comment by joeybaker** [comment]
Thanks for merging #1 @bjoerge. I updated this PR so it merges cleanly.

**Comment by bjoerge** [comment]
Fantastic, thanks a lot. Will publish a new version in a moment.

**Comment by bjoerge** [comment]
Published 0.2.0

**Comment by joeybaker** [comment]
Cheers! I'll be able to get atomify/atomify-js#67 out now. Thank you!

**Pull request merged**
